### ISSUE TITLE
download NTU RGB+D dataset？？

### ISSUE THREAD

**Issue by lunalulu** [huguyuehuhu/HCN-pytorch#10]
Thanks for the work you've done！
Due to an error of the NUT data set server, I have not applied for the download of the data set. Could you please send me the data set?

thanks very much~

**Comment by huguyuehuhu** [comment]
Sorry, I have no right to share this dataset, you need to apply from its [official site](http://rose1.ntu.edu.sg/Datasets/actionRecognition.asp).

**Comment by lunalulu** [comment]
@huguyuehuhu ok, thanks
