### ISSUE TITLE
fps?

### ISSUE THREAD

**Issue by lunalulu** [huguyuehuhu/HCN-pytorch#11]
thanks for your great work!
Please tell me the running time of this algorithm?thanks

**Comment by huguyuehuhu** [comment]
I do not remember it  exactly, but there are four training logs (`train.log`) in  ./experiments/..., eg. `experiments/NTU-RGB-D-CS/HCN01/train.log`.  you can read the rough running time from it.

**Comment by lunalulu** [comment]
thanks~
