### ISSUE TITLE
Trouble with running

### ISSUE THREAD

**Issue by YuzheHao** [huguyuehuhu/HCN-pytorch#15]
After transforming the raw data and moving the json file, I tried to run the training program in the README. But it keep sending "[Errno 99] Cannot assign requested address" all the time.
At first, I thought it's due to I didn't launch visdom, I use "python -m visdom.server" to launch, it informs me "Application Started" and I CANNOT input instruction after this information.
I hope I could get some help about how to deal with the error  "[Errno 99] Cannot assign requested address" and launching visdom.

**Comment by huguyuehuhu** [comment]
1. Following the procedure and issues in [official site of visdom ](https://github.com/facebookresearch/visdom), use its test example to ensure you have installed visdom correct. 
2. Or, to ignore the error, you can comment the visdom-related code, but these will no longer produce curves.
