### ISSUE TITLE
How do you normalize the length of sequence?

### ISSUE THREAD

**Issue by lwj2018** [huguyuehuhu/HCN-pytorch#24]
How do you handle the various length of sequence? by downsampling?

**Comment by huguyuehuhu** [comment]
During training: 1. Random cropping 2. Resize by 'bilinear'  interpolation ; 
During testing: 1. Center cropping 2. Resize by 'bilinear'  interpolation .
Refer the  [code](https://github.com/huguyuehuhu/HCN-pytorch/blob/fd1380b1f6d7becc743ac3944d955144d5cbcaae/feeder/tools.py#L50)  for the details.
