### ISSUE TITLE
Only using 2 people skeleton sequence?

### ISSUE THREAD

**Issue by Peter654q** [huguyuehuhu/HCN-pytorch#3]
Hi,

I want to ask that are you only using 2  people skeleton sequence on training and testing?
If I want to use the data include 1 person and multi-people, how can I do?

Thanks!

**Comment by huguyuehuhu** [comment]
@Peter654q  My code use variable numbers of people ( one or two), when there is  only one person, we fill all the positions of the second person with 0. Similarly,  when you  have at most N persons, you can define input  tensor with position for all N persons,  and fill 0 for the sequences which the number is smaller than N.

**Comment by Peter654q** [comment]
Thanks for your replication!
