### ISSUE TITLE
Current state working?

### ISSUE THREAD

**Issue by maxstrobel** [huguyuehuhu/HCN-pytorch#4]
Hi,

I have trouble running the code of the current state in the repo.

1. To preprocess the data, the imports in feeder have to be adapted.
2. PyTorch should not be installed via pip. Pip forces a version that is maybe not compatible to the GPU and the system. The corresponding version should be installed manually, to match the hardware. In my case the proposed pip version introduced an delay of 5 minutes after loading the dataset and did not work.
3. Maybe add a note, that a running visdom server is needed.
4. Maybe there is an issue, with certifi from requirements.txt, but I am not sure, wheter it is an problem on my side, so i excluded that from the pull request.

I make a pull request fixing 2,3. The imports are very confusing, maybe you could fix that.

Thanks & Best,
Max

**Comment by huguyuehuhu** [comment]
@maxstrobel 
1. I have added  a `try...except` to make it adaptive. 
2. Thank you for your suggestions and  contributions,  I have merged it into Master branch.
