### ISSUE TITLE
the download of dataset

### ISSUE THREAD

**Issue by Tylerjoe** [huguyuehuhu/HCN-pytorch#7]
![ntu](https://user-images.githubusercontent.com/11598641/51664717-01410e00-1ff5-11e9-9c0d-17bd5b70d946.png)
I have a simple problem about dataset download.
the total dataset is 1.3TB, it means we need download all the datasets ? or only part of them ,such as 3D skeletons(5.8GB)
Thanks!

**Comment by huguyuehuhu** [comment]
@Tylerjoe Only skeletons is  required.

**Comment by Tylerjoe** [comment]
Thanks
