### ISSUE TITLE
How to deal with absent data

### ISSUE THREAD

**Issue by pyni** [huguyuehuhu/HCN-pytorch#9]
Hello, i have a question:

If my data are absent,(for example, the skeletons for some frames are absent or some joints are absent in a frame ), how to deal with these cases.

Thanks!

**Comment by huguyuehuhu** [comment]
1. You can interpolate the missing frame or joints with their neighbors 
2. Alternatively, you can directly fill them with zeros (then they  will contribute nothing to the network forward path), OR with their nearest neighbor (assuming that the movement is continuous ).

**Comment by pyni** [comment]
Thanks for replying

**Comment by pyni** [comment]
Hi, i am sorry to disturb you a gain.
i wonder whether you will publish your action detection algorithm?

**Comment by huguyuehuhu** [comment]
@pyni  I am not the author of the original paper, I have only  reproduced the recognition  part, you can try to contact the authors the paper.
